auth0:
  domain: dev-yn2m1l5yklr21ie4.eu.auth0.com
  clientId: zQiPlx8zDqd1Umcrwh6zjEX3DpbKwotL
  clientSecret: lU5Ka9yx_jaGeTL7phFrow20NFkkvMIrccwkGxXWjbHMIt5FM3HT3_z_TXwTFEEV
  audience: https://my-hotel-booking-api

spring:
  application:
    name: hotel-booking
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: qwfm
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: development, production
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-yn2m1l5yklr21ie4.eu.auth0.com/.well-known/jwks.json
logging:
  level:
    org:
      example:
        hotelbooking=DEBUG: